<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0-rc.2.25502.107" />
    <PackageReference Include="Serilog" Version="4.3.1-dev-02387" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.3-dev-02320" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.1-dev-00953" />
  </ItemGroup>

</Project>
